Ave = FALSE
x = c(0,1,-1);
P = expand.grid(x=0:2,y=0:2,z=0:2)
U = expand.grid(x,x,x)

fname = paste("f",P$x,P$y,P$z,sep="")
AddDensity(
	name = fname,
	dx   = U[,1],
	dy   = U[,2],
	dz   = U[,3],
	comment=paste("density F",1:27-1),
	group="f"
)

for (f in fname[U[,1]<0]) AddField(f,dx=-1,dy=0,dz=0) # Make f accessible in left neighbour for the wierd outlet condition

AddQuantity( name="Rho",unit="kg/m3")
AddQuantity( name="U",unit="m/s",vector=T)

AddSetting(name="nu", default=0.16666666, comment='Viscosity')
AddSetting(name="nubuffer",default=0.01, comment='Viscosity in the buffer layer')
AddSetting(name="Velocity", default="0m/s", comment='Inlet velocity', zonal=TRUE)
AddSetting(name="Pressure", default="0Pa", comment='Inlet pressure', zonal=TRUE)

AddSetting(name="GalileanCorrection",default=1.,comment='Galilean correction term')
AddSetting(name="ForceX",default=0,comment='Force force X')
AddSetting(name="ForceY",default=0,comment='Force force Y')
AddSetting(name="ForceZ",default=0,comment='Force force Z')
AddSetting(name="Size_Lx",default=0,comment='Lx size of domain')
AddSetting(name="Size_Ly",default=0,comment='Ly size of domain')
AddSetting(name="Size_Lz",default=0,comment='Lz size of domain')

AddGlobal(name="Flux", comment='Volume flux', unit="m3/s")

AddNodeType("SymmetryY", "BOUNDARY")
AddNodeType("SymmetryZ", "BOUNDARY")
AddNodeType("TopSymmetry","BOUNDARY")
AddNodeType("BottomSymmetry","BOUNDARY")
AddNodeType("NVelocity", "BOUNDARY")
AddNodeType("SVelocity", "BOUNDARY")
AddNodeType("NPressure", "BOUNDARY")
AddNodeType("SPressure", "BOUNDARY")

# new boundary conditions
#AddNodeType("CoutVelocity","BOUNDARY")
#AddNodeType("PCoutVelocity","BOUNDARY")

AddNodeType("EOutlet","BOUNDARY")
AddNodeType("WVelocityEq","BOUNDARY")
AddNodeType("WVelocityBB","BOUNDARY")

AddNodeType("QIBB",group="HO_BOUNDARY")

#reporting fluxes
AddNodeType("XYslice1",group="ADDITIONALS")
AddNodeType("XZslice1",group="ADDITIONALS")
AddNodeType("YZslice1",group="ADDITIONALS")
AddNodeType("XYslice2",group="ADDITIONALS")
AddNodeType("XZslice2",group="ADDITIONALS")
AddNodeType("YZslice2",group="ADDITIONALS")

AddGlobal(name="TotalRho", comment='Total mass', unit="kg")

AddGlobal(name="XYvx", comment='Volume flux', unit="m3/s")
AddGlobal(name="XYvy", comment='Volume flux', unit="m3/s")
AddGlobal(name="XYvz", comment='Volume flux', unit="m3/s")
AddGlobal(name="XYrho1", comment='Volume flux', unit="kg/m")
AddGlobal(name="XYrho2", comment='Volume flux', unit="kg/m")
AddGlobal(name="XYarea", comment='Volume flux', unit="m2")

AddGlobal(name="XZvx", comment='Volume flux', unit="m3/s")
AddGlobal(name="XZvy", comment='Volume flux', unit="m3/s")
AddGlobal(name="XZvz", comment='Volume flux', unit="m3/s")
AddGlobal(name="XZrho1", comment='Volume flux', unit="kg/m")
AddGlobal(name="XZrho2", comment='Volume flux', unit="kg/m")
AddGlobal(name="XZarea", comment='Volume flux', unit="m2")

AddGlobal(name="YZvx", comment='Volume flux', unit="m3/s")
AddGlobal(name="YZvy", comment='Volume flux', unit="m3/s")
AddGlobal(name="YZvz", comment='Volume flux', unit="m3/s")
AddGlobal(name="YZrho1", comment='Volume flux', unit="kg/m")
AddGlobal(name="YZrho2", comment='Volume flux', unit="kg/m")
AddGlobal(name="YZarea", comment='Volume flux', unit="m2")

#reporting point data
AddNodeType("Point01",group="ADDITIONALS")
AddNodeType("Point02",group="ADDITIONALS")
AddNodeType("Point03",group="ADDITIONALS")
AddNodeType("Point04",group="ADDITIONALS")
#AddNodeType("Point05",group="#AddITIONALS")
#AddNodeType("Point06",group="#AddITIONALS")
#AddNodeType("Point07",group="#AddITIONALS")
#AddNodeType("Point08",group="#AddITIONALS")
#AddNodeType("Point09",group="#AddITIONALS")
#AddNodeType("Point10",group="#AddITIONALS")
#AddNodeType("Point11",group="#AddITIONALS")
#AddNodeType("Point12",group="#AddITIONALS")
#AddNodeType("Point13",group="#AddITIONALS")
#AddNodeType("Point14",group="#AddITIONALS")
#AddNodeType("Point15",group="#AddITIONALS")
#AddNodeType("Point16",group="#AddITIONALS")
#AddNodeType("Point17",group="#AddITIONALS")
#AddNodeType("Point18",group="#AddITIONALS")
#AddNodeType("Point19",group="#AddITIONALS")
#AddNodeType("Point20",group="#AddITIONALS")

# quantities reported to point data
AddGlobal(name="Point01Rho", comment='Point density', unit="kg/m3")
AddGlobal(name="Point02Rho", comment='Point density', unit="kg/m3")
AddGlobal(name="Point03Rho", comment='Point density', unit="kg/m3")
AddGlobal(name="Point04Rho", comment='Point density', unit="kg/m3")
#AddGlobal(name="Point05Rho", comment='Point density', unit="kg/m3")
#AddGlobal(name="Point06Rho", comment='Point density', unit="kg/m3")
#AddGlobal(name="Point07Rho", comment='Point density', unit="kg/m3")
#AddGlobal(name="Point08Rho", comment='Point density', unit="kg/m3")
#AddGlobal(name="Point09Rho", comment='Point density', unit="kg/m3")
#AddGlobal(name="Point10Rho", comment='Point density', unit="kg/m3")
#AddGlobal(name="Point11Rho", comment='Point density', unit="kg/m3")
#AddGlobal(name="Point12Rho", comment='Point density', unit="kg/m3")
#AddGlobal(name="Point13Rho", comment='Point density', unit="kg/m3")
#AddGlobal(name="Point14Rho", comment='Point density', unit="kg/m3")
#AddGlobal(name="Point15Rho", comment='Point density', unit="kg/m3")
#AddGlobal(name="Point16Rho", comment='Point density', unit="kg/m3")
#AddGlobal(name="Point17Rho", comment='Point density', unit="kg/m3")
#AddGlobal(name="Point18Rho", comment='Point density', unit="kg/m3")
#AddGlobal(name="Point19Rho", comment='Point density', unit="kg/m3")
#AddGlobal(name="Point20Rho", comment='Point density', unit="kg/m3")

#AddGlobal(name="Point01Ux", comment='Ux', unit="m/s")
#AddGlobal(name="Point02Ux", comment='Ux', unit="m/s")
#AddGlobal(name="Point03Ux", comment='Ux', unit="m/s")
#AddGlobal(name="Point04Ux", comment='Ux', unit="m/s")
#AddGlobal(name="Point05Ux", comment='Ux', unit="m/s")
#AddGlobal(name="Point06Ux", comment='Ux', unit="m/s")
#AddGlobal(name="Point07Ux", comment='Ux', unit="m/s")
#AddGlobal(name="Point08Ux", comment='Ux', unit="m/s")
#AddGlobal(name="Point09Ux", comment='Ux', unit="m/s")
#AddGlobal(name="Point10Ux", comment='Ux', unit="m/s")
#AddGlobal(name="Point11Ux", comment='Ux', unit="m/s")
#AddGlobal(name="Point12Ux", comment='Ux', unit="m/s")
#AddGlobal(name="Point13Ux", comment='Ux', unit="m/s")
#AddGlobal(name="Point14Ux", comment='Ux', unit="m/s")
#AddGlobal(name="Point15Ux", comment='Ux', unit="m/s")
#AddGlobal(name="Point16Ux", comment='Ux', unit="m/s")
#AddGlobal(name="Point17Ux", comment='Ux', unit="m/s")
#AddGlobal(name="Point18Ux", comment='Ux', unit="m/s")
#AddGlobal(name="Point19Ux", comment='Ux', unit="m/s")
#AddGlobal(name="Point20Ux", comment='Ux', unit="m/s")

#AddGlobal(name="Point01Uy", comment='Uy', unit="m/s")
#AddGlobal(name="Point02Uy", comment='Uy', unit="m/s")
#AddGlobal(name="Point03Uy", comment='Uy', unit="m/s")
#AddGlobal(name="Point04Uy", comment='Uy', unit="m/s")
#AddGlobal(name="Point05Uy", comment='Uy', unit="m/s")
#AddGlobal(name="Point06Uy", comment='Uy', unit="m/s")
#AddGlobal(name="Point07Uy", comment='Uy', unit="m/s")
#AddGlobal(name="Point08Uy", comment='Uy', unit="m/s")
#AddGlobal(name="Point09Uy", comment='Uy', unit="m/s")
#AddGlobal(name="Point10Uy", comment='Uy', unit="m/s")
#AddGlobal(name="Point11Uy", comment='Uy', unit="m/s")
#AddGlobal(name="Point12Uy", comment='Uy', unit="m/s")
#AddGlobal(name="Point13Uy", comment='Uy', unit="m/s")
#AddGlobal(name="Point14Uy", comment='Uy', unit="m/s")
#AddGlobal(name="Point15Uy", comment='Uy', unit="m/s")
#AddGlobal(name="Point16Uy", comment='Uy', unit="m/s")
#AddGlobal(name="Point17Uy", comment='Uy', unit="m/s")
#AddGlobal(name="Point18Uy", comment='Uy', unit="m/s")
#AddGlobal(name="Point19Uy", comment='Uy', unit="m/s")
#AddGlobal(name="Point20Uy", comment='Uy', unit="m/s")


#AddGlobal(name="Point01Uz", comment='Uz', unit="m/s")
#AddGlobal(name="Point02Uz", comment='Uz', unit="m/s")
#AddGlobal(name="Point03Uz", comment='Uz', unit="m/s")
#AddGlobal(name="Point04Uz", comment='Uz', unit="m/s")
#AddGlobal(name="Point05Uz", comment='Uz', unit="m/s")
#AddGlobal(name="Point06Uz", comment='Uz', unit="m/s")
#AddGlobal(name="Point07Uz", comment='Uz', unit="m/s")
#AddGlobal(name="Point08Uz", comment='Uz', unit="m/s")
#AddGlobal(name="Point09Uz", comment='Uz', unit="m/s")
#AddGlobal(name="Point10Uz", comment='Uz', unit="m/s")
#AddGlobal(name="Point11Uz", comment='Uz', unit="m/s")
#AddGlobal(name="Point12Uz", comment='Uz', unit="m/s")
#AddGlobal(name="Point13Uz", comment='Uz', unit="m/s")
#AddGlobal(name="Point14Uz", comment='Uz', unit="m/s")
#AddGlobal(name="Point15Uz", comment='Uz', unit="m/s")
#AddGlobal(name="Point16Uz", comment='Uz', unit="m/s")
#AddGlobal(name="Point17Uz", comment='Uz', unit="m/s")
#AddGlobal(name="Point18Uz", comment='Uz', unit="m/s")
#AddGlobal(name="Point19Uz", comment='Uz', unit="m/s")
#AddGlobal(name="Point20Uz", comment='Uz', unit="m/s")


